# Generated by Django 5.2.11 on 2026-02-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_venta', models.IntegerField()),
                ('precio_costo', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
